version: "3.9"
services:
  python-docker-polyglot-world:
    build:
      context: python/.
      dockerfile: python.Dockerfile
    ports:
      - "8081:80"
  nodejs-docker-polyglot-world:
    build:
      context: nodejs/.
      dockerfile: nodejs.Dockerfile
    ports:
      - "8082:8080"
  go-docker-polyglot-world:
    build:
      context: go/.
      dockerfile: go.Dockerfile
    ports:
      - "8083:8080"
  deno-docker-polyglot-world:
    build:
      context: deno/.
      dockerfile: deno.Dockerfile
    ports:
      - "8084:8080"
  rust-docker-polyglot-world:
    build:
      context: rust/.
      dockerfile: rust.Dockerfile
    ports:
      - "8085:3000"
  crystal-docker-polyglot-world:
    build:
      context: crystal/.
      dockerfile: crystal.Dockerfile
    ports:
      - "8086:8080"
