version: "3.9"
services:
  nginx-postman:
    container_name: nginx-postman
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hello-world.json:/usr/share/nginx/html/hello-world.json:ro
  python-docker-polyglot-world:
    build:
      context: .
      dockerfile: python/python.Dockerfile
    ports:
      - "8081:8080"
  go-docker-polyglot-world:
    build:
      context: .
      dockerfile: go/go.Dockerfile
    ports:
      - "8083:8080"
  nodejs-docker-polyglot-world:
    build:
      context: .
      dockerfile: nodejs/nodejs.Dockerfile
    ports:
      - "8082:8080"
  rust-docker-polyglot-world:
    build:
      context: .
      dockerfile: rust/rust.Dockerfile
    ports:
      - "8085:8080"
  deno-docker-polyglot-world:
    build:
      context: .
      dockerfile: deno/deno.Dockerfile
    ports:
      - "8084:8080"
  crystal-docker-polyglot-world:
    build:
      context: .
      dockerfile: crystal/crystal.Dockerfile
    ports:
      - "8086:8080"
