version: "3.9"
services:
  python-docker-polyglot-world:
    build:
      context: .
      dockerfile: python/python.Dockerfile
    ports:
      - "8081:8080"
  go-docker-polyglot-world:
    build:
      context: .
      dockerfile: go/go.Dockerfile
    ports:
      - "8083:8080"
  nodejs-docker-polyglot-world:
    build:
      context: .
      dockerfile: nodejs/nodejs.Dockerfile
    ports:
      - "8082:8080"
  deno-docker-polyglot-world:
    build:
      context: deno/.
      dockerfile: deno.Dockerfile
    ports:
      - "8084:8080"
  rust-docker-polyglot-world:
    build:
      context: rust/.
      dockerfile: rust.Dockerfile
    ports:
      - "8085:8080"
  crystal-docker-polyglot-world:
    build:
      context: crystal/.
      dockerfile: crystal.Dockerfile
    ports:
      - "8086:8080"
